steps:

  # Docker Build and Tag to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Docker Build

  # Docker Push to GCR
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
    id: Docker Push

  # Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'filen-drive-service'  # Replace with the desired Cloud Run service name
    - '--image'
    - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA' 
    - '--region'
    - 'us-central1'  # Replace with your desired region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'  # Optional: remove if you want to require authentication

# This ensures the image is available in Cloud Build's cache for faster builds
images:
  - 'gcr.io/$PROJECT_ID/_IMAGE_NAME:$SHORT_SHA'

substitutions:
  _GCR_HOSTNAME: gcr.io
  _IMAGE_NAME: filen-drive
  _SHORT_SHA: $SHORT_SHA